name: Simple-Factions
version: 0.1
author: Jitse3301.
description: A simple factions plugin made by Jitse3301.
main: net.jitse.simplefactions.SimpleFactions
depend: [Vault]
commands:
  factions:
    description: Main simple-factions command.
    aliases: [faction, f]